<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\berita;
use App\Models\Contact;
use App\Models\Tentang;
use App\Models\User;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // berita::factory(8)->create();
        // Berita::create([
        //     'title' => 'Bintang Albie',
        //     'isi' => 'test1@example.com',
        //     'image' => 'sanket-shah-SVA7TyHxojY-unsplash'
        // ]);

        Berita::create([
            'id' => '1',
            'title' => 'Satu',
            'isi' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum esse ab reprehenderit, laborum nesciunt dignissimos at aut debitis, sapiente vero alias eum delectus dolores nihil dolorem voluptate atque nostrum. Laudantium, rerum a asperiores nisi praesentium et. Architecto, maxime expedita, eligendi mollitia sapiente quos voluptatibus veritatis doloribus excepturi consequatur reiciendis asperiores fugiat, porro corrupti! Adipisci magni ipsum rem architecto, dolor corporis. Dicta blanditiis sunt quod, ratione molestiae voluptate sed aliquam quibusdam maxime dignissimos ad inventore sint sequi natus voluptatibus non ipsam accusantium. Delectus, eius, vitae asperiores expedita voluptate itaque modi voluptas unde cum suscipit accusamus atque eos exercitationem soluta cumque. Adipisci error deleniti iusto, laborum qui dolorum facilis doloremque dolorem reprehenderit quisquam sequi eos obcaecati quam nemo. Expedita corporis esse odio nostrum ex unde dignissimos, aperiam placeat impedit nihil laudantium perferendis rem corrupti odit vel, dicta dolorum ducimus inventore iure earum officiis sint aliquam aliquid. Expedita placeat corporis corrupti. Numquam excepturi provident nulla aspernatur voluptate quaerat facere. Nostrum itaque pariatur explicabo molestias recusandae nobis nisi quod cumque eveniet laudantium, dolore fugiat! Et ad asperiores quae nihil minima possimus fuga necessitatibus atque dignissimos enim, reprehenderit modi? Dolore sint minus amet at laboriosam excepturi deleniti enim ex expedita voluptate adipisci incidunt ipsam recusandae reiciendis, mollitia, cum similique impedit cupiditate deserunt molestias! Repudiandae iste velit adipisci deleniti dolorum molestias non itaque quaerat eveniet, obcaecati nisi, ullam consequatur omnis nam? Dolores aperiam facere et, velit suscipit fuga illo consequuntur tempora fugit quod. Aperiam maiores corrupti omnis, vel quis sequi quod fugiat. Et nulla dolore officia similique. Sequi cumque repellat inventore! Impedit, accusantium quam ducimus optio fuga enim fugit alias iste iure nihil laborum! Fugiat explicabo obcaecati consequatur laborum praesentium ipsa! Possimus enim minima reprehenderit officiis quis deleniti eligendi perspiciatis eum, quibusdam magni, voluptates animi a porro aperiam accusantium voluptatem maiores earum? Et esse exercitationem voluptatibus?',
            'image' => 'fathul-abrar-T-qI_MI2EMA-unsplash.jpg'
        ]);
        Berita::create([
            'id' => '2',
            'title' => 'Dua',
            'isi' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum esse ab reprehenderit, laborum nesciunt dignissimos at aut debitis, sapiente vero alias eum delectus dolores nihil dolorem voluptate atque nostrum. Laudantium, rerum a asperiores nisi praesentium et. Architecto, maxime expedita, eligendi mollitia sapiente quos voluptatibus veritatis doloribus excepturi consequatur reiciendis asperiores fugiat, porro corrupti! Adipisci magni ipsum rem architecto, dolor corporis. Dicta blanditiis sunt quod, ratione molestiae voluptate sed aliquam quibusdam maxime dignissimos ad inventore sint sequi natus voluptatibus non ipsam accusantium. Delectus, eius, vitae asperiores expedita voluptate itaque modi voluptas unde cum suscipit accusamus atque eos exercitationem soluta cumque. Adipisci error deleniti iusto, laborum qui dolorum facilis doloremque dolorem reprehenderit quisquam sequi eos obcaecati quam nemo. Expedita corporis esse odio nostrum ex unde dignissimos, aperiam placeat impedit nihil laudantium perferendis rem corrupti odit vel, dicta dolorum ducimus inventore iure earum officiis sint aliquam aliquid. Expedita placeat corporis corrupti. Numquam excepturi provident nulla aspernatur voluptate quaerat facere. Nostrum itaque pariatur explicabo molestias recusandae nobis nisi quod cumque eveniet laudantium, dolore fugiat! Et ad asperiores quae nihil minima possimus fuga necessitatibus atque dignissimos enim, reprehenderit modi? Dolore sint minus amet at laboriosam excepturi deleniti enim ex expedita voluptate adipisci incidunt ipsam recusandae reiciendis, mollitia, cum similique impedit cupiditate deserunt molestias! Repudiandae iste velit adipisci deleniti dolorum molestias non itaque quaerat eveniet, obcaecati nisi, ullam consequatur omnis nam? Dolores aperiam facere et, velit suscipit fuga illo consequuntur tempora fugit quod. Aperiam maiores corrupti omnis, vel quis sequi quod fugiat. Et nulla dolore officia similique. Sequi cumque repellat inventore! Impedit, accusantium quam ducimus optio fuga enim fugit alias iste iure nihil laborum! Fugiat explicabo obcaecati consequatur laborum praesentium ipsa! Possimus enim minima reprehenderit officiis quis deleniti eligendi perspiciatis eum, quibusdam magni, voluptates animi a porro aperiam accusantium voluptatem maiores earum? Et esse exercitationem voluptatibus?',
            'image' => 'sanket-shah-SVA7TyHxojY-unsplash.jpg'
        ]);
        Berita::create([
            'id' => '3',
            'title' => 'Tiga',
            'isi' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum esse ab reprehenderit, laborum nesciunt dignissimos at aut debitis, sapiente vero alias eum delectus dolores nihil dolorem voluptate atque nostrum. Laudantium, rerum a asperiores nisi praesentium et. Architecto, maxime expedita, eligendi mollitia sapiente quos voluptatibus veritatis doloribus excepturi consequatur reiciendis asperiores fugiat, porro corrupti! Adipisci magni ipsum rem architecto, dolor corporis. Dicta blanditiis sunt quod, ratione molestiae voluptate sed aliquam quibusdam maxime dignissimos ad inventore sint sequi natus voluptatibus non ipsam accusantium. Delectus, eius, vitae asperiores expedita voluptate itaque modi voluptas unde cum suscipit accusamus atque eos exercitationem soluta cumque. Adipisci error deleniti iusto, laborum qui dolorum facilis doloremque dolorem reprehenderit quisquam sequi eos obcaecati quam nemo. Expedita corporis esse odio nostrum ex unde dignissimos, aperiam placeat impedit nihil laudantium perferendis rem corrupti odit vel, dicta dolorum ducimus inventore iure earum officiis sint aliquam aliquid. Expedita placeat corporis corrupti. Numquam excepturi provident nulla aspernatur voluptate quaerat facere. Nostrum itaque pariatur explicabo molestias recusandae nobis nisi quod cumque eveniet laudantium, dolore fugiat! Et ad asperiores quae nihil minima possimus fuga necessitatibus atque dignissimos enim, reprehenderit modi? Dolore sint minus amet at laboriosam excepturi deleniti enim ex expedita voluptate adipisci incidunt ipsam recusandae reiciendis, mollitia, cum similique impedit cupiditate deserunt molestias! Repudiandae iste velit adipisci deleniti dolorum molestias non itaque quaerat eveniet, obcaecati nisi, ullam consequatur omnis nam? Dolores aperiam facere et, velit suscipit fuga illo consequuntur tempora fugit quod. Aperiam maiores corrupti omnis, vel quis sequi quod fugiat. Et nulla dolore officia similique. Sequi cumque repellat inventore! Impedit, accusantium quam ducimus optio fuga enim fugit alias iste iure nihil laborum! Fugiat explicabo obcaecati consequatur laborum praesentium ipsa! Possimus enim minima reprehenderit officiis quis deleniti eligendi perspiciatis eum, quibusdam magni, voluptates animi a porro aperiam accusantium voluptatem maiores earum? Et esse exercitationem voluptatibus?',
            'image' => 'sebastian-coman-photography-eBmyH7oO5wY-unsplash.jpg'
        ]);
        Berita::create([
            'id' => '4',
            'title' => 'Empat',
            'isi' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum esse ab reprehenderit, laborum nesciunt dignissimos at aut debitis, sapiente vero alias eum delectus dolores nihil dolorem voluptate atque nostrum. Laudantium, rerum a asperiores nisi praesentium et. Architecto, maxime expedita, eligendi mollitia sapiente quos voluptatibus veritatis doloribus excepturi consequatur reiciendis asperiores fugiat, porro corrupti! Adipisci magni ipsum rem architecto, dolor corporis. Dicta blanditiis sunt quod, ratione molestiae voluptate sed aliquam quibusdam maxime dignissimos ad inventore sint sequi natus voluptatibus non ipsam accusantium. Delectus, eius, vitae asperiores expedita voluptate itaque modi voluptas unde cum suscipit accusamus atque eos exercitationem soluta cumque. Adipisci error deleniti iusto, laborum qui dolorum facilis doloremque dolorem reprehenderit quisquam sequi eos obcaecati quam nemo. Expedita corporis esse odio nostrum ex unde dignissimos, aperiam placeat impedit nihil laudantium perferendis rem corrupti odit vel, dicta dolorum ducimus inventore iure earum officiis sint aliquam aliquid. Expedita placeat corporis corrupti. Numquam excepturi provident nulla aspernatur voluptate quaerat facere. Nostrum itaque pariatur explicabo molestias recusandae nobis nisi quod cumque eveniet laudantium, dolore fugiat! Et ad asperiores quae nihil minima possimus fuga necessitatibus atque dignissimos enim, reprehenderit modi? Dolore sint minus amet at laboriosam excepturi deleniti enim ex expedita voluptate adipisci incidunt ipsam recusandae reiciendis, mollitia, cum similique impedit cupiditate deserunt molestias! Repudiandae iste velit adipisci deleniti dolorum molestias non itaque quaerat eveniet, obcaecati nisi, ullam consequatur omnis nam? Dolores aperiam facere et, velit suscipit fuga illo consequuntur tempora fugit quod. Aperiam maiores corrupti omnis, vel quis sequi quod fugiat. Et nulla dolore officia similique. Sequi cumque repellat inventore! Impedit, accusantium quam ducimus optio fuga enim fugit alias iste iure nihil laborum! Fugiat explicabo obcaecati consequatur laborum praesentium ipsa! Possimus enim minima reprehenderit officiis quis deleniti eligendi perspiciatis eum, quibusdam magni, voluptates animi a porro aperiam accusantium voluptatem maiores earum? Et esse exercitationem voluptatibus?',
            'image' => 'jimmy-dean-Jvw3pxgeiZw-unsplash.jpg'
        ]);
        Berita::create([
            'id' => '5',
            'title' => 'Lima',
            'isi' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum esse ab reprehenderit, laborum nesciunt dignissimos at aut debitis, sapiente vero alias eum delectus dolores nihil dolorem voluptate atque nostrum. Laudantium, rerum a asperiores nisi praesentium et. Architecto, maxime expedita, eligendi mollitia sapiente quos voluptatibus veritatis doloribus excepturi consequatur reiciendis asperiores fugiat, porro corrupti! Adipisci magni ipsum rem architecto, dolor corporis. Dicta blanditiis sunt quod, ratione molestiae voluptate sed aliquam quibusdam maxime dignissimos ad inventore sint sequi natus voluptatibus non ipsam accusantium. Delectus, eius, vitae asperiores expedita voluptate itaque modi voluptas unde cum suscipit accusamus atque eos exercitationem soluta cumque. Adipisci error deleniti iusto, laborum qui dolorum facilis doloremque dolorem reprehenderit quisquam sequi eos obcaecati quam nemo. Expedita corporis esse odio nostrum ex unde dignissimos, aperiam placeat impedit nihil laudantium perferendis rem corrupti odit vel, dicta dolorum ducimus inventore iure earum officiis sint aliquam aliquid. Expedita placeat corporis corrupti. Numquam excepturi provident nulla aspernatur voluptate quaerat facere. Nostrum itaque pariatur explicabo molestias recusandae nobis nisi quod cumque eveniet laudantium, dolore fugiat! Et ad asperiores quae nihil minima possimus fuga necessitatibus atque dignissimos enim, reprehenderit modi? Dolore sint minus amet at laboriosam excepturi deleniti enim ex expedita voluptate adipisci incidunt ipsam recusandae reiciendis, mollitia, cum similique impedit cupiditate deserunt molestias! Repudiandae iste velit adipisci deleniti dolorum molestias non itaque quaerat eveniet, obcaecati nisi, ullam consequatur omnis nam? Dolores aperiam facere et, velit suscipit fuga illo consequuntur tempora fugit quod. Aperiam maiores corrupti omnis, vel quis sequi quod fugiat. Et nulla dolore officia similique. Sequi cumque repellat inventore! Impedit, accusantium quam ducimus optio fuga enim fugit alias iste iure nihil laborum! Fugiat explicabo obcaecati consequatur laborum praesentium ipsa! Possimus enim minima reprehenderit officiis quis deleniti eligendi perspiciatis eum, quibusdam magni, voluptates animi a porro aperiam accusantium voluptatem maiores earum? Et esse exercitationem voluptatibus?',
            'image' => 'fathul-abrar-T-qI_MI2EMA-unsplash.jpg'
        ]);
        Berita::create([
            'id' => '6',
            'title' => 'Enam',
            'isi' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum esse ab reprehenderit, laborum nesciunt dignissimos at aut debitis, sapiente vero alias eum delectus dolores nihil dolorem voluptate atque nostrum. Laudantium, rerum a asperiores nisi praesentium et. Architecto, maxime expedita, eligendi mollitia sapiente quos voluptatibus veritatis doloribus excepturi consequatur reiciendis asperiores fugiat, porro corrupti! Adipisci magni ipsum rem architecto, dolor corporis. Dicta blanditiis sunt quod, ratione molestiae voluptate sed aliquam quibusdam maxime dignissimos ad inventore sint sequi natus voluptatibus non ipsam accusantium. Delectus, eius, vitae asperiores expedita voluptate itaque modi voluptas unde cum suscipit accusamus atque eos exercitationem soluta cumque. Adipisci error deleniti iusto, laborum qui dolorum facilis doloremque dolorem reprehenderit quisquam sequi eos obcaecati quam nemo. Expedita corporis esse odio nostrum ex unde dignissimos, aperiam placeat impedit nihil laudantium perferendis rem corrupti odit vel, dicta dolorum ducimus inventore iure earum officiis sint aliquam aliquid. Expedita placeat corporis corrupti. Numquam excepturi provident nulla aspernatur voluptate quaerat facere. Nostrum itaque pariatur explicabo molestias recusandae nobis nisi quod cumque eveniet laudantium, dolore fugiat! Et ad asperiores quae nihil minima possimus fuga necessitatibus atque dignissimos enim, reprehenderit modi? Dolore sint minus amet at laboriosam excepturi deleniti enim ex expedita voluptate adipisci incidunt ipsam recusandae reiciendis, mollitia, cum similique impedit cupiditate deserunt molestias! Repudiandae iste velit adipisci deleniti dolorum molestias non itaque quaerat eveniet, obcaecati nisi, ullam consequatur omnis nam? Dolores aperiam facere et, velit suscipit fuga illo consequuntur tempora fugit quod. Aperiam maiores corrupti omnis, vel quis sequi quod fugiat. Et nulla dolore officia similique. Sequi cumque repellat inventore! Impedit, accusantium quam ducimus optio fuga enim fugit alias iste iure nihil laborum! Fugiat explicabo obcaecati consequatur laborum praesentium ipsa! Possimus enim minima reprehenderit officiis quis deleniti eligendi perspiciatis eum, quibusdam magni, voluptates animi a porro aperiam accusantium voluptatem maiores earum? Et esse exercitationem voluptatibus?',
            'image' => 'sanket-shah-SVA7TyHxojY-unsplash.jpg'
        ]);
        Berita::create([
            'id' => '7',
            'title' => 'Tujuh',
            'isi' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum esse ab reprehenderit, laborum nesciunt dignissimos at aut debitis, sapiente vero alias eum delectus dolores nihil dolorem voluptate atque nostrum. Laudantium, rerum a asperiores nisi praesentium et. Architecto, maxime expedita, eligendi mollitia sapiente quos voluptatibus veritatis doloribus excepturi consequatur reiciendis asperiores fugiat, porro corrupti! Adipisci magni ipsum rem architecto, dolor corporis. Dicta blanditiis sunt quod, ratione molestiae voluptate sed aliquam quibusdam maxime dignissimos ad inventore sint sequi natus voluptatibus non ipsam accusantium. Delectus, eius, vitae asperiores expedita voluptate itaque modi voluptas unde cum suscipit accusamus atque eos exercitationem soluta cumque. Adipisci error deleniti iusto, laborum qui dolorum facilis doloremque dolorem reprehenderit quisquam sequi eos obcaecati quam nemo. Expedita corporis esse odio nostrum ex unde dignissimos, aperiam placeat impedit nihil laudantium perferendis rem corrupti odit vel, dicta dolorum ducimus inventore iure earum officiis sint aliquam aliquid. Expedita placeat corporis corrupti. Numquam excepturi provident nulla aspernatur voluptate quaerat facere. Nostrum itaque pariatur explicabo molestias recusandae nobis nisi quod cumque eveniet laudantium, dolore fugiat! Et ad asperiores quae nihil minima possimus fuga necessitatibus atque dignissimos enim, reprehenderit modi? Dolore sint minus amet at laboriosam excepturi deleniti enim ex expedita voluptate adipisci incidunt ipsam recusandae reiciendis, mollitia, cum similique impedit cupiditate deserunt molestias! Repudiandae iste velit adipisci deleniti dolorum molestias non itaque quaerat eveniet, obcaecati nisi, ullam consequatur omnis nam? Dolores aperiam facere et, velit suscipit fuga illo consequuntur tempora fugit quod. Aperiam maiores corrupti omnis, vel quis sequi quod fugiat. Et nulla dolore officia similique. Sequi cumque repellat inventore! Impedit, accusantium quam ducimus optio fuga enim fugit alias iste iure nihil laborum! Fugiat explicabo obcaecati consequatur laborum praesentium ipsa! Possimus enim minima reprehenderit officiis quis deleniti eligendi perspiciatis eum, quibusdam magni, voluptates animi a porro aperiam accusantium voluptatem maiores earum? Et esse exercitationem voluptatibus?',
            'image' => 'anh-nguyen-kcA-c3f_3FE-unsplash.jpg'
        ]);
        Berita::create([
            'id' => '8',
            'title' => 'Delapan',
            'isi' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum esse ab reprehenderit, laborum nesciunt dignissimos at aut debitis, sapiente vero alias eum delectus dolores nihil dolorem voluptate atque nostrum. Laudantium, rerum a asperiores nisi praesentium et. Architecto, maxime expedita, eligendi mollitia sapiente quos voluptatibus veritatis doloribus excepturi consequatur reiciendis asperiores fugiat, porro corrupti! Adipisci magni ipsum rem architecto, dolor corporis. Dicta blanditiis sunt quod, ratione molestiae voluptate sed aliquam quibusdam maxime dignissimos ad inventore sint sequi natus voluptatibus non ipsam accusantium. Delectus, eius, vitae asperiores expedita voluptate itaque modi voluptas unde cum suscipit accusamus atque eos exercitationem soluta cumque. Adipisci error deleniti iusto, laborum qui dolorum facilis doloremque dolorem reprehenderit quisquam sequi eos obcaecati quam nemo. Expedita corporis esse odio nostrum ex unde dignissimos, aperiam placeat impedit nihil laudantium perferendis rem corrupti odit vel, dicta dolorum ducimus inventore iure earum officiis sint aliquam aliquid. Expedita placeat corporis corrupti. Numquam excepturi provident nulla aspernatur voluptate quaerat facere. Nostrum itaque pariatur explicabo molestias recusandae nobis nisi quod cumque eveniet laudantium, dolore fugiat! Et ad asperiores quae nihil minima possimus fuga necessitatibus atque dignissimos enim, reprehenderit modi? Dolore sint minus amet at laboriosam excepturi deleniti enim ex expedita voluptate adipisci incidunt ipsam recusandae reiciendis, mollitia, cum similique impedit cupiditate deserunt molestias! Repudiandae iste velit adipisci deleniti dolorum molestias non itaque quaerat eveniet, obcaecati nisi, ullam consequatur omnis nam? Dolores aperiam facere et, velit suscipit fuga illo consequuntur tempora fugit quod. Aperiam maiores corrupti omnis, vel quis sequi quod fugiat. Et nulla dolore officia similique. Sequi cumque repellat inventore! Impedit, accusantium quam ducimus optio fuga enim fugit alias iste iure nihil laborum! Fugiat explicabo obcaecati consequatur laborum praesentium ipsa! Possimus enim minima reprehenderit officiis quis deleniti eligendi perspiciatis eum, quibusdam magni, voluptates animi a porro aperiam accusantium voluptatem maiores earum? Et esse exercitationem voluptatibus?',
            'image' => 'brooke-lark-1Rm9GLHV0UA-unsplash.jpg'
        ]);
        Berita::create([
            'id' => '9',
            'title' => 'Delapan',
            'isi' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum esse ab reprehenderit, laborum nesciunt dignissimos at aut debitis, sapiente vero alias eum delectus dolores nihil dolorem voluptate atque nostrum. Laudantium, rerum a asperiores nisi praesentium et. Architecto, maxime expedita, eligendi mollitia sapiente quos voluptatibus veritatis doloribus excepturi consequatur reiciendis asperiores fugiat, porro corrupti! Adipisci magni ipsum rem architecto, dolor corporis. Dicta blanditiis sunt quod, ratione molestiae voluptate sed aliquam quibusdam maxime dignissimos ad inventore sint sequi natus voluptatibus non ipsam accusantium. Delectus, eius, vitae asperiores expedita voluptate itaque modi voluptas unde cum suscipit accusamus atque eos exercitationem soluta cumque. Adipisci error deleniti iusto, laborum qui dolorum facilis doloremque dolorem reprehenderit quisquam sequi eos obcaecati quam nemo. Expedita corporis esse odio nostrum ex unde dignissimos, aperiam placeat impedit nihil laudantium perferendis rem corrupti odit vel, dicta dolorum ducimus inventore iure earum officiis sint aliquam aliquid. Expedita placeat corporis corrupti. Numquam excepturi provident nulla aspernatur voluptate quaerat facere. Nostrum itaque pariatur explicabo molestias recusandae nobis nisi quod cumque eveniet laudantium, dolore fugiat! Et ad asperiores quae nihil minima possimus fuga necessitatibus atque dignissimos enim, reprehenderit modi? Dolore sint minus amet at laboriosam excepturi deleniti enim ex expedita voluptate adipisci incidunt ipsam recusandae reiciendis, mollitia, cum similique impedit cupiditate deserunt molestias! Repudiandae iste velit adipisci deleniti dolorum molestias non itaque quaerat eveniet, obcaecati nisi, ullam consequatur omnis nam? Dolores aperiam facere et, velit suscipit fuga illo consequuntur tempora fugit quod. Aperiam maiores corrupti omnis, vel quis sequi quod fugiat. Et nulla dolore officia similique. Sequi cumque repellat inventore! Impedit, accusantium quam ducimus optio fuga enim fugit alias iste iure nihil laborum! Fugiat explicabo obcaecati consequatur laborum praesentium ipsa! Possimus enim minima reprehenderit officiis quis deleniti eligendi perspiciatis eum, quibusdam magni, voluptates animi a porro aperiam accusantium voluptatem maiores earum? Et esse exercitationem voluptatibus?',
            'image' => 'sanket-shah-SVA7TyHxojY-unsplash.jpg'
        ]);

        Contact::create([
            'id' => '1',
            'email' => 'bintangalbi26@gmail.com',
            'phone' => '+62 8964 8112 615',
            'location' => 'Kota Bandung, Jawa Barat'
        ]);

        Tentang::create([
            'id' => '1',
            'visi' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae quisquam officia, consequuntur eveniet dicta aperiam labore! Eligendi inventore consequuntur aut libero numquam! Dolore labore doloremque necessitatibus modi facere distinctio tempora pariatur amet quia saepe, nemo tempore itaque fuga voluptate architecto rerum reprehenderit id harum doloribus perferendis similique. Quas facere corrupti, ea animi, repellendus dicta suscipit ducimus architecto laborum, illo itaque. Quo minus sint libero officiis ipsam accusantium architecto pariatur eos.',
            'misi' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis tenetur ipsa perspiciatis similique magnam iste maiores! Quam debitis explicabo autem commodi iste ut deserunt, quae reprehenderit distinctio enim placeat exercitationem iusto nesciunt eius eum nostrum voluptatum, accusamus repudiandae possimus quibusdam, et adipisci tempora? Placeat modi perspiciatis perferendis quo laboriosam totam dolore cupiditate explicabo a debitis voluptas error rerum distinctio cumque molestiae eveniet saepe, molestias numquam non earum repellat itaque. Laboriosam.'
        ]);

        User::create([
            'username' => 'bintang',
            'email' => 'bintang@gmail.com',
            'password' => 'albinidi26'
        ]);
    }
}
